### PR TITLE
Add more Starting Units

### PR DESCRIPTION
**Pull request by MustaphaTR**
Adds Medium and Heavy starting units, Renames MCV Only and Light Support.

### CODE REVIEW

**Comment by phrohdoh** [comment]
Did RA2 have this many starting classes, or did it use the slider `0..10`?
If the latter, I'd rather not take this and instead implement a point value pool.
@abcdefg30, if you think this would be better to have instead of a slider, please let that be known.
This can be accepted if it is the better way forward.

**Comment by MustaphaTR** [comment]
All Command & Conquer and Dune games have slider for starting unit counts. But all of current OpenRA mods are using this kind of starting units. (In fact all except TS has no Medium Support)

**Comment by abcdefg30** [comment]
Looks good to me. :+1: / :white_check_mark:

**Comment by phrohdoh** [comment]
That reasoning works well for me, thanks guys.

**Pull request merged**
