### PR TITLE
Infantry Fighting Vehicle transforms on passenger

### PR DESCRIPTION
**Pull request by DnAp**
Infantry Fighting Vehicle transforms on passenger http://gfycat.com/IllinformedMammothGrayfox

### CODE REVIEW

**Comment by GraionDilach** [comment]
:-1:

**Bad idea.** IFV's should be implemented via granting upgrades, not via Transforms. See the discussion at http://ppmforums.com/viewtopic.php?p=538503#538503 for a more suitable way.

**Comment by penev92** [comment]
Just to give some background: transforming is bad in general, as it has some inherent ... "bugs" that can't be worked around, so it should be avoided.

**Comment by phrohdoh** [comment]
It is not bad in general.
It has its uses just like upgrades do.

Transforms should be used when you do not care about preserving actor state.

**Comment by Mailaender** [comment]
Superseded by https://github.com/OpenRA/ra2/pull/78.

**Pull request closed without merging**
