### PR TITLE
Engineer don't sabotage

### PR DESCRIPTION
**Pull request by DnAp**
Engineer sabotage = false

### CODE REVIEW

**Comment by MustaphaTR** [comment]
This fixes #61, isn't it?

**Comment by DnAp** [comment]
Yes.

**Comment by MustaphaTR** [comment]
:+1:

**Comment by Iamgoofball** [comment]
https://github.com/OpenRA/ra2/pull/1

**Comment by abcdefg30** [comment]
This was merged: https://github.com/OpenRA/ra2/pull/8

**Pull request closed without merging**
