### PR TITLE
Finish IronCurtain.

### PR DESCRIPTION
**Pull request by GraionDilach**
Only the cursor remains. Target area is properly 3x3 now as it was in RA2 and it kills infantry as intended.

### CODE REVIEW

**Comment by ghost** [comment]
- Animations based on support power status aren't implemented properly: when built, i.
- Support power charge time is too short (5 minutes, isn't it?)
- Does not stop charging/use when powered down
- My testing indicates that the range is not working correctly. I'm having difficulty targeting buildings unless I click them directly.
- Attempting to curtain the IC building itself causes it to explode (?!?)

**Comment by GraionDilach** [comment]
Animation state for the 1 min cooldown state and Ready state needs to be implemented at upstream first.
I assumed @MustaphaTR set up `RequiresPower` and the charge time right, will get fixed.
I think the building range is caused by that buildings have small hitboxes, that'll need the hitshape PR to be merged for upstream/increase hitradii for buildings to fix.
I'll check out that IC building destroy bug.

**Comment by GraionDilach** [comment]
Fixed IC building dying and SW charging. Also good find, HealthPercentageDamageWarhead is bugged in upstream.

**Comment by ghost** [comment]
Out of curiosity, what was the IC self-destruction issue?

For animations, is it not a local bug also that the IC displays the active animation when first built?
- Infantry standing on the sub-cells farthest away from the detonation are unaffected.

**Comment by ghost** [comment]
- The `RequiresPower` attribute appears not to have changed much. It still works fine without.

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/pull/9842 is the bug which I kinda evaded with listing the IC effect before the infantry killing warhead - I forgot `AffectsParent` on the IC effect so the "infantry killer" warhead which ignores stances/TargetTypes - that's the bug -  killed it.

I take a rest then I look at this again.

**Comment by GraionDilach** [comment]
Tweaked range again. Can't repro unpowered IC still charging.

**Comment by Iamgoofball** [comment]
https://github.com/OpenRA/ra2/pull/1

**Comment by GraionDilach** [comment]
I'm fine with that. Closing this then.

**Comment by Mailaender** [comment]
This was resolved with an upgrade support power instead. Do we still want this for other stuff?

**Comment by GraionDilach** [comment]
The upgrade support power cannot give the 3x3 area and IIRC lacked some stuff, not sure what now.

YR GenMutator and PsychicDominator won't come soon so I guess this is a really low priority.

**Pull request closed without merging**
