### PR TITLE
Make Construction Yards emit Engineers when sold

### PR DESCRIPTION
**Pull request by MustaphaTR**

### CODE REVIEW

**Comment by phrohdoh** [comment]
Can someone confirm that these actors match the original?

**Comment by GraionDilach** [comment]
Approximately yes. The problem is that TS/RA2 did this in an entirely different way - they calculated the infantry gained runtime by grabbing the building's `Cost`, dividing it with the side's `SurvivorDivisor` (see 
https://github.com/Phrohdoh/oramod-ra2/blob/master/extra-files/rules.ini#L44) and spawn the result amount of the side's crew https://github.com/Phrohdoh/oramod-ra2/blob/master/extra-files/rules.ini#L179

If the building was a Conyard there was a 25% chance per infantry that this unit becomes the `Engineer` instead of the `*Crew`, if this was armed (had a `Primary` weapon) the chance would render the infantry into a `Technician`.

**Comment by phrohdoh** [comment]
Ah yes I remember these calculations.
I'd like to implement that and the starting units slider at some point.
@MustaphaTR please fix your typo in the commit message so I can merge this.
`Enginner` -> `Engineeer`

**Comment by MustaphaTR** [comment]
Fixed typo on commit message.

> `Engineeer`

There is typo here too. :P

**Comment by phrohdoh** [comment]
One more change to ask of you.
Could you make it so that soviet players always get soviet units, and allied players always get allied units?

**Comment by MustaphaTR** [comment]
That's already like this. There is no `SENGINEER` in OpenRA yet and it's not really required their only difference is voice lines.

**Comment by phrohdoh** [comment]
You're right; I misread. Thanks!

**Pull request merged**
