### PR TITLE
Fix Mirage Tank Weapon Impact Anim

### PR DESCRIPTION
**Pull request by MustaphaTR**
It was using wrong anim.

### CODE REVIEW

**Comment by phrohdoh** [comment]
Can you squash these commits please?

**Comment by MustaphaTR** [comment]
Be patient, i'm trying to do but Github for Windows gone mad again.

**Comment by penev92** [comment]
I suggest _not_ using GitHub for Windows. As far as I know nobody is happy with that.
My client of choice is GitExtensions.

**Comment by MustaphaTR** [comment]
Squashed Commits.

**Comment by abcdefg30** [comment]
We don't want splashes when hitting water?

**Comment by MustaphaTR** [comment]
Same anim plays when attacked to water in Orginal RA2 iirc, but i should take a look.

Edit: I checked, it plays same animation on water, not water splash.

**Comment by GraionDilach** [comment]
Yes, Mirage Tank was like that. :+1:

**Comment by phrohdoh** [comment]
Was there some limitation that caused this, or was it intentional?

In my opinion there's no reason not to use splash animations when projectiles hit water tiles.

**Comment by GraionDilach** [comment]
Intentional. This was an energy weapon and not a projectile.

**Comment by GraionDilach** [comment]
On a second thought... SmallCrater should be removed from it's smudge as well though.

**Comment by MustaphaTR** [comment]
Updated.

**Comment by Xinayder** [comment]
Just a thought: is it supposed to remove impact sounds? Checking the diff looks like you removed the impact sound for `Warhead@2Eff`.

**Comment by MustaphaTR** [comment]
Hmm... Art.ini says `IronCurtainDeflect` is animation's sound. https://github.com/MustaphaTR/oramod-ra2/blob/master/extra-files/art.ini#L11503 but it is possibly just because of same anim is also Iron Curatin Deflect animation. As it have speed of 100 (instant hit) seperate sound for impact isn't required.

**Comment by phrohdoh** [comment]
This was manually merged into 8f2934c2f0b56b8b68aadaa7d3535060c3c60831, but the good news is that I figured out how to keep the commit under your name!

**Pull request closed without merging**
